# Generated by Django 5.0.7 on 2024-07-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
