# Generated by Django 4.2.16 on 2025-05-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_placeholder'),
        ('teachers', '0005_cleanup_teacher_data'),
    ]

    operations = [
    ]
